import { makeStyles } from "@mui/styles";

const useStyle = makeStyles(() => ({
  root: {},
  card: {
    width: "100%",
    overflow: "visible !important",
    borderRadius:"10px !important",
  },
  ul: {
    display: "flex",
    width: "100%",
    justifyContent: "space-between",
    listStyle: "none",
  },
  li: {
    textAlign: "start",
    display: "flex",
    flexDirection: "column",
  },
  filterLabel: {
    color: "white !important",
    marginTop:'-25px !important',
    fontSize: "17px !important",
    fontWeight: "600 !important",
    fontFamily:'Poppins, sans-serif !important',
  },
  locationSelect: {
    width: "100%",
    overflow: "hidden",
    border: "none",
    position: "relative",
    padding: "10px 0px",
    color: "green !important",
    outline: "none",
    fontSize: "18px",
    background: 'transparent',
    fontFamily:'Poppins, sans-serif !important',
  },
  travelFrom: {
    width: "100%",
    overflow: "hidden",
    border: "none",
    position: "relative",
    padding: "10px 0px",
    color: "green",
    outline: "none",
    fontSize: "18px",
    background: 'transparent',
    fontFamily:'Poppins, sans-serif !important',
  },
  to: {
    width: "100%",
    overflow: "hidden",
    border: "none",
    position: "relative",
    padding: "10px 0px",
    color: "green !important",
    outline: "none",
    fontSize: "18px",
        background: 'transparent',fontFamily:'Poppins, sans-serif !important',
  },
  roomSelector: {
    width: "100%",
    overflow: "hidden",
    border: "none",
    position: "relative",
    padding: "10px 0px",
    color: "green !important",
    outline: "none",
    fontSize: "18px",
    background: 'transparent',
    fontFamily:'Poppins, sans-serif !important',
  },
  adultSelector: {
    width: "100%",
    overflow: "hidden",
    border: "none",
    position: "relative",
    padding: "10px 0px",
    color: "green !important",
    outline: "none",
    fontSize: "18px",
    background: 'transparent',
    fontFamily:'Poppins, sans-serif !important',
  },
  child: {
    width: "100%",
    overflow: "hidden",
    border: "none",
    position: "relative",
    padding: "10px 0px",
    color: "green",
    outline: "none",
    fontSize: "18px",
    background: 'transparent',
    fontFamily:'Poppins, sans-serif !important',
  },
  btn: {
    height: "100%",
    background: "linear-gradient(45deg, #29b33f, #7ee9bdd4)",
    border: "none",
    padding: "15px",
    width: "200px",
    marginTop:'25px',
    borderRadius:"0px 10px 10px 0px !important",
    color:"white",
    fontWeight:"700",
    fontFamily:'Poppins, sans-serif !important',
    cursor: 'pointer',
  },
  tableCell: {
    padding: "0px !important",
    border: "2px solid white",
  },
}));

export default useStyle;
